name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERBOSE: 1

jobs:
  build-all:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
          os:
            - Windows
            - macOS
            - linux
          compiler:
            - g++
            - clang++
            - cl
          build_type:
            - Release
            - Debug
          language:
            - c++23
          generator:
            - "Ninja"
          
          exclude:
            - os: Windows
              compiler: g++
            - os: Windows
              compiler: clang++
            - os: Linux
              compiler: cl
            - os: macOS
              compiler: g++
            - os: macOS
              compiler: cl
              
          include:
            - os: Windows
              language: c++23
            - os: Linux
              language: c++23
            - os: macOS
              language: c++23
    steps:
      - uses: actions/checkout@v3
        
      - name: Configure CMake
        env:
          CC: ${{matrix.compiler}}
          CXX: ${{matrix.compiler}}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=${{matrix.compiler}}  -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -S ${{github.workspace}} -G "${{matrix.generator}}"
      - name: Build
        env:
          CC: ${{matrix.compiler}}
          CXX: ${{matrix.compiler}}
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target all --
      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{matrix.build_type}}
