name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERBOSE: 1

jobs:
  build-all:
    runs-on: self-hosted, ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
          os: [Windows,macOS,linux]
          compiler: [g++,clang++]
          build_type: [Debug,Release]
          langver: [c++23]
          generator: ["Ninja"]
          
          exclude:
            - os: macOS
              compiler: g++
              langver: c++23
            - os: Windows
              compiler: g++
            - os: Windows
              compiler: clang++
              
          include:
            - os: Windows
              compiler: msvc
              langver: c++23

    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        env:
          CXX: ${{matrix.compiler}}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -S ${{github.workspace}} -G "${{matrix.generator}}"
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target all --
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}}
