name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERBOSE: 1

jobs:
  build-all:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
          os:
            - Windows
            - macOS
            - linux
          compiler:
            - gcc
            - clang
            - msvc
          generator:
            - "Ninja Multi-Config"
          build_type:
            - Release
            - Debug
          language:
            - C++23

          exclude:
            - os: Windows
              compiler: gcc
            - os: Windows
              compiler: clang
            - os: Linux
              compiler: msvc
            - os: macOS
              compiler: gcc
            - os: macOS
              compiler: msvc
    steps:
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -S ${{github.workspace}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target all --
      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{matrix.build_type}}
