name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERBOSE: 1

jobs:
  build-all:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
          os:
            - Windows
            - macOS
            - linux
          compiler:
            - gcc
            - clang
            - cl
          build_type:
            - Release
            - Debug
          language:
            - c++23
          generator:
            - "Ninja"
          
          exclude:
            - os: Windows
              compiler: gcc
            - os: Windows
              compiler: clang
            - os: Linux
              compiler: cl
            - os: macOS
              compiler: gcc
            - os: macOS
              compiler: cl
              
          include:
            - os: Windows
              env:
                CC: cl
                CXX: cl
              language: c++23
            - os: Linux
              env:
                CC: gcc
                CXX: g++
              language: c++23
            - os: macOS
              env:
                CC: clang
                CXX: clang
              language: c++23
    steps:
      - uses: actions/checkout@v3
      - name: Detect Compiler Info (clean files)
        run: |
          git clean -d -f -q -x
          mkdir ${{github.workspace}}/build
          cd ${{github.workspace}}/build
          cmake ..
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -S ${{github.workspace}} -G "${{matrix.generator}}"
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target all --
      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{matrix.build_type}}
